### ISSUE TITLE
ArcheType

### ISSUE THREAD

**Issue by Boughten52** [Mehdows/D7049E-game-engine#12]
Archetypes are collections of component types that define behavior and properties of entities. They are used for efficient storage since they enable the engine to store entities of the same type in contiguous memory blocks. The entity's components are then stored in an array in memory in a specific order that is defined by the Archetype.

**Comment by arek-e** [comment]
> Are the ArcheTypes currently used when storing entities?

Answered in #15. But if they are going to be used for storage we might have to iterate again on this issue
