### ISSUE TITLE
EntityManager

### ISSUE THREAD

**Issue by Boughten52** [Mehdows/D7049E-game-engine#15]
The EntityManager manages creation, deletion and storage of entities. ArcheTypes are typically used to define the data layout and behavior of entities (an ArcheType is a collection of component types). When a new entity is created, the EntityManager assigns it to the appropriate ArcheType based on the types of components it has.

**Comment by Boughten52** [comment]
Are the ArcheTypes currently used when storing entities?

**Comment by arek-e** [comment]
No, archetypes are only used to query entities that have the components types defined in them. It utilizes the componentManager to return the component array of a given component. Inside each component array there is a list of integer id's connected to entities using the component

**Comment by arek-e** [comment]
Using the function `CreateEntityWithArchetype()` that takes a archetype as argument, the EntityManager singleton can create entities with a given archetype
